apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: whispering-orangutan-python
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:837afae6439fb9162159d7801ea4925a4f41867d@sha256:09bf656af2e065af9c109108d6a92cb35ff20061c4ce7e274ee1a2b038662b6c
        name: container-image  
