apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: whispering-orangutan-python 
  janus-idp.io/tekton: whispering-orangutan-python
  backstage.io/kubernetes-id: whispering-orangutan-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: whispering-orangutan-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  