apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: whispering-orangutan-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whispering-orangutan-python 
  name: whispering-orangutan-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: whispering-orangutan-python
    weight: 100 
