apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: whispering-orangutan-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whispering-orangutan-python 
  name: whispering-orangutan-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: whispering-orangutan-python 
